<a href="https://colab.research.google.com/github/PaolaMaribel18/RI_2024a/blob/main/week4/taller02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Taller 02: Modelo de Espacio Vectorial

## Objetivo
 Comprender y aplicar el Modelo de Espacio Vectorial para el ranking de documentos
 basado en la similitud de contenido con una consulta dada.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


###  Parte 1: Preparación de Datos


In [2]:
import os
import numpy as np
import re

CORPUS_DIR = '/content/drive/MyDrive/ri_2024a/week4/data'

documents_text = {}

dictionary = {}

for filename in os.listdir(CORPUS_DIR):
    if filename.endswith('.txt'):
        file_path = os.path.join(CORPUS_DIR, filename)
        with open(file_path, 'r', encoding='utf-8') as file:
            text = file.read().lower()  # Lee y convierte a minúsculas
            text = re.sub(r'[.,:;]', '', text)
            text = re.sub(r'[^a-zA-ZñÑáéíóú\s]', '', text)  # Elimina caracteres no alfanuméricos
            documents_text[filename] = text
            # Construye el diccionario de términos
            words = text.split()
            for word in words:
                dictionary[word] = True

In [3]:
term_document_matrix = np.zeros((len(dictionary), len(documents_text)), dtype=int)

term_index_mapping = {term: idx for idx, term in enumerate(dictionary)}

for doc_idx, (doc_name, doc_text) in enumerate(documents_text.items()):
    words = doc_text.split()
    for word in words:
        if word in term_index_mapping:
            term_idx = term_index_mapping[word]
            term_document_matrix[term_idx, doc_idx] += 1


In [4]:
print(term_document_matrix)

[[2 0 0 ... 0 1 0]
 [4 0 1 ... 0 0 0]
 [2 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]


In [5]:
import csv

csv_file = '/content/drive/MyDrive/ri_2024a/week4/term_document_matrix.csv'

# Guarda la matriz en el archivo CSV
with open(csv_file, 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['Term'] + list(documents_text.keys()))
    for term, term_counts in zip(dictionary.keys(), term_document_matrix):
        writer.writerow([term] + list(term_counts))

In [14]:
import pandas as pd
df_1 = pd.read_csv(csv_file)
print(df_1)

            Term  t3.txt  t5.txt  t2.txt  t1.txt  t4.txt  t6.txt  t7.txt  \
0          museo       2       0       0       0       0       0       0   
1            del       4       0       1       1       2       0       1   
2          prado       2       0       0       0       0       0       0   
3             el       2       1       3       0       3       0       3   
4             es       1       1       2       0       1       2       1   
..           ...     ...     ...     ...     ...     ...     ...     ...   
370     especies       0       0       0       0       0       0       0   
371   amenazadas       0       0       0       0       0       0       0   
372  proporciona       0       0       0       0       0       0       0   
373    educativa       0       0       0       0       0       0       0   
374  entretenida       0       0       0       0       0       0       0   

     t10.txt  t9.txt  ...  t12.txt  t11.txt  t14.txt  t18.txt  t17.txt  \
0          0 

#  Parte 2: Análisis de Consultas


In [7]:
# Lista de líneas queries
lineas = [
    "Historia medieval de las ciudades europeas",
    "Principales destinos turísticos en Europa",
    "Influencia de la realeza en la cultura europea",
    "Importancia de los parques urbanos en las ciudades",
    "Gastronomía típica en capitales europeas",
    "Eventos deportivos icónicos en Europa",
    "Celebraciones de Navidad en ciudades europeas",
    "Museos de arte importantes en Europa",
    "Efectos de la Segunda Guerra Mundial en ciudades europeas",
    "Arquitectura histórica en ciudades europeas",
    "Clubes de fútbol famosos y sus estadios en Europa",
    "Transformación urbana y regeneración de espacios",
    "Tradición cervecera en ciudades europeas",
    "Mercados y comercio tradicional en Europa",
    "Centros de arte y creatividad en ciudades modernas",
    "Actividades de ocio y entretenimiento en ciudades metropolitanas",
    "Conservación de la naturaleza y la vida silvestre en zonas urbanas",
    "Planificación de eventos culturales y festivales en ciudades",
    "Desarrollo del transporte y la infraestructura urbana",
    "Impacto de la tecnología en la vida urbana"
]

In [8]:
# Crear una matriz vacía para almacenar los conteos de términos en las líneas
term_query_matrix = np.zeros((len(dictionary), len(lineas)), dtype=int)

# Recorre las líneas y llena la matriz con los conteos de términos
for line_idx, line in enumerate(lineas):
    words = line.lower().split()  # Convertir a minúsculas y dividir en palabras
    for word in words:
        if word in term_index_mapping:
            term_idx = term_index_mapping[word]
            term_query_matrix[term_idx, line_idx] += 1


In [9]:
print(term_query_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [16]:
csv_file_q = '/content/drive/MyDrive/ri_2024a/week4/term_query_matrix.csv'

# Guarda la matriz en el archivo CSV
with open(csv_file_q, 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['Term'] + [f'Line {i+1}' for i in range(len(lineas))])
    for term, term_counts in zip(dictionary.keys(), term_query_matrix):
        writer.writerow([term] + list(term_counts))

In [17]:
df_2 = pd.read_csv(csv_file_q)
print(df_2)

            Term  Line 1  Line 2  Line 3  Line 4  Line 5  Line 6  Line 7  \
0          museo       0       0       0       0       0       0       0   
1            del       0       0       0       0       0       0       0   
2          prado       0       0       0       0       0       0       0   
3             el       0       0       0       0       0       0       0   
4             es       0       0       0       0       0       0       0   
..           ...     ...     ...     ...     ...     ...     ...     ...   
370     especies       0       0       0       0       0       0       0   
371   amenazadas       0       0       0       0       0       0       0   
372  proporciona       0       0       0       0       0       0       0   
373    educativa       0       0       0       0       0       0       0   
374  entretenida       0       0       0       0       0       0       0   

     Line 8  Line 9  ...  Line 11  Line 12  Line 13  Line 14  Line 15  \
0         0   

### Parte 3: Cálculo de Similitud y Ranking


In [19]:
# Función para calcular la similitud (distancia coseno)
def cosine_similarity(vec1, vec2):
    dot_product = np.dot(vec1, vec2)
    norm_vec1 = np.linalg.norm(vec1)
    norm_vec2 = np.linalg.norm(vec2)
    return dot_product / (norm_vec1 * norm_vec2) if norm_vec1 != 0 and norm_vec2 != 0 else 0

# Calcular la similitud(distancia coseno) entre cada consulta y cada documento
similarity_matrix = np.zeros((len(lineas), len(documents_text)))

for query_idx in range(len(lineas)):
    query_vector = term_query_matrix[:, query_idx]
    for doc_idx in range(len(documents_text)):
        doc_vector = term_document_matrix[:, doc_idx]
        similarity_matrix[query_idx, doc_idx] = cosine_similarity(query_vector, doc_vector)


In [20]:
# Ordenar los documentos por relevancia para cada consulta
ordered_documents = {}

for query_idx, line in enumerate(lineas):
    doc_similarities = [(doc_name, similarity_matrix[query_idx, doc_idx]) for doc_idx, doc_name in enumerate(documents_text.keys())]
    doc_similarities.sort(key=lambda x: x[1], reverse=True)
    ordered_documents[line] = doc_similarities

for query, ranked_docs in ordered_documents.items():
    print(f"Consulta: {query}")
    for doc_name, similarity in ranked_docs:
        print(f"  Documento: {doc_name}, Similitud: {similarity:.4f}")
    print()

Consulta: Historia medieval de las ciudades europeas
  Documento: t2.txt, Similitud: 0.4058
  Documento: t1.txt, Similitud: 0.3572
  Documento: t14.txt, Similitud: 0.3525
  Documento: t18.txt, Similitud: 0.3283
  Documento: t12.txt, Similitud: 0.3162
  Documento: t9.txt, Similitud: 0.3145
  Documento: t15.txt, Similitud: 0.3030
  Documento: t20.txt, Similitud: 0.2795
  Documento: t6.txt, Similitud: 0.2774
  Documento: t11.txt, Similitud: 0.2500
  Documento: t4.txt, Similitud: 0.2408
  Documento: t17.txt, Similitud: 0.2294
  Documento: t3.txt, Similitud: 0.1780
  Documento: t5.txt, Similitud: 0.1644
  Documento: t7.txt, Similitud: 0.1599
  Documento: t16.txt, Similitud: 0.1599
  Documento: t10.txt, Similitud: 0.1213
  Documento: t13.txt, Similitud: 0.0949
  Documento: t8.txt, Similitud: 0.0693
  Documento: t19.txt, Similitud: 0.0635

Consulta: Principales destinos turísticos en Europa
  Documento: t11.txt, Similitud: 0.2652
  Documento: t12.txt, Similitud: 0.2236
  Documento: t13.txt, S